
output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: GRAKN.AI
# this appears on the top navigation bar next to the home button

site_title: GRAKN.AI
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: GRAKN.AI
# this appears in the footer

github_editme_path: graknlabs/grakn/tree/master/docs
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: UA-72414051-1

# disqus_shortname: idrbwjekyll
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4005
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

plugins: [jekyll-coffeescript]

sass:
  sass_dir: css

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - api.yml
  - config.ru
  - feed.xml
  - Procfile
  - PULL_REQUEST_TEMPLATE.md
  - Rakefile
  - README.md
  - static.json
  - to-do-list.md
  - tooltips.json
  - pdfconfigs
  - pdf-template.sh
  - _config-template.yml
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/old/

# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: GRAKN.AI Feedback

feedback_email: info@grakn.ai
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
  00-general:
    output: true
  01-overview:
    output: true
  02-running-grakn:
    output: true
  03-client-api:
    output: true
  04-cloud-deployment:
    output: true
  05-management:
    output: true
  06-workbase:
    output: true
  07-examples:
    output: true
  08-schema:
    output: true
  09-query:
    output: true
  10-reasoning:
    output: true
  11-analytics:
    output: true
  12-developer-guidelines-a:
    output: true
  13-developer-guidelines-b:
    output: true
collections_dir: docs

defaults:
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      tooltip: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "00-general"
    values:
      layout: "page"
      category: ""
      section: ""
  -
    scope:
      path: ""
      type: "01-overview"
    values:
      layout: "page"
      category: "Database"
      section: "Overview"
  -
    scope:
      path: ""
      type: "02-running-grakn"
    values:
      layout: "page"
      category: "Database"
      section: "Running Grakn"
  -
    scope:
      path: ""
      type: "03-client-api"
    values:
      layout: "page"
      category: "Database"
      section: "Client API"
  -
    scope:
      path: ""
      type: "04-cloud-deployment"
    values:
      layout: "page"
      category: "Database"
      section: "Cloud Deployment"
  -
    scope:
      path: ""
      type: "05-management"
    values:
      layout: "page"
      category: "Database"
      section: "Management"
  -
    scope:
      path: ""
      type: "06-workbase"
    values:
      layout: "page"
      category: "Database"
      section: "Workbase"
  -
    scope:
      path: ""
      type: "07-examples"
    values:
      layout: "page"
      category: "Database"
      section: "Examples"
  -
    scope:
      path: ""
      type: "08-schema"
    values:
      layout: "page"
      category: "Graql"
      section: "Schema"
  -
    scope:
      path: ""
      type: "09-query"
    values:
      layout: "page"
      category: "Graql"
      section: "Query"
  -
    scope:
      path: ""
      type: "10-reasoning"
    values:
      layout: "page"
      category: "Graql"
      section: "Reasoning"
  -
    scope:
      path: ""
      type: "11-analytics"
    values:
      layout: "page"
      category: "Graql"
      section: "Analytics"
  -
    scope:
      path: ""
      type: "12-developer-guidelines-a"
    values:
      layout: "page"
      category: "Dev Guidelines"
      section: "Developer Guidelines A"
  -
    scope:
      path: ""
      type: "13-developer-guidelines-b"
    values:
      layout: "page"
      category: "Dev Guidelines"
      section: "Developer Guidelines B"

# these are defaults used for the frontmatter for these file types

sidebars:
- documentation_sidebar
- overview_sidebar
- contributors_sidebar
- academy_sidebar

description: "A Distributed Knowledge Graph"
# the description is used in the feed.xml file

# needed for sitemap.xml file only
url: http://grakn.ai/pages/
