site:
  title: TypeDB Documentation portal
  start_page: home:ROOT:index.adoc
  robots: allow
content:
  edit_url: 'https://github.com/typedb/typedb-docs/edit/development/{path}'
  sources:
    - url: .
      start_path: content/2.x/drivers
      branches: HEAD
    - url: .
      start_path: content/2.x/typeql
      branches: HEAD
    - url: .
      start_path: content/2.x/manual
      branches: HEAD
    - url: .
      start_path: content/2.x/academy
      branches: HEAD
    - url: .
      start_path: content/2.x/home
      branches: HEAD
    - url: https://github.com/typedb/typedb-driver
      start_path: docs
      branches: [master, "2.29.2"]
    - url: .
      start_path: content/3.x/drivers
      branches: HEAD
    - url: .
      start_path: content/3.x/typeql
      branches: HEAD
    - url: .
      start_path: content/3.x/manual
      branches: HEAD
    - url: .
      start_path: content/3.x/academy
      branches: HEAD
    - url: .
      start_path: content/3.x/home
      branches: HEAD
urls:
  latest_version_segment: ""
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: "@"
    source-highlighter: ~
  extensions:
    - "@asciidoctor/tabs"
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./dist
