site:
  title: TypeDB Documentation portal
  start_page: typedb:ROOT:home/overview.adoc
  robots: allow
content:
  sources:
    - url: .
      start_path: content/typedb-src
      branches: HEAD
    - url: .
      start_path: content/clients-src
      branches: HEAD
    - url: .
      start_path: content/typeql-src
      branches: HEAD
urls:
  latest_version_segment: ""
antora:
  extensions:
    - "@antora/lunr-extension"
asciidoc:
  attributes:
    page-pagination: "@"
    source-highlighter: ~
  extensions:
    - "@asciidoctor/tabs"
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./dist
