[build]
  command = "npm run build-ci"
  ignore = "/bin/false"

[build.processing.html]
  pretty_urls = false

[[redirects]]
from = "https://development--typedb-docs.netlify.app/*"
to = "https://development.typedb.com/docs/:splat"
status = 301
force = true
