[build]
  command = "npm run build-ci"
  ignore = "/bin/false"

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "development--typedb-docs.netlify.app/*"
  [headers.values]
    X-Robots-Tag = "noindex"
