"use strict";

// Maps a page URL to the URL of its Markdown twin generated by build-llms.js.
// Handles both URL styles: indexify ("/foo/" -> "/foo/index.md", used in CI)
// and plain ("/foo.html" -> "/foo.md", used in local builds).
module.exports = (url) => {
    if (!url) return url;
    if (url.endsWith("/")) return url + "index.md";
    return url.replace(/\.html$/, ".md");
};
